### ISSUE TITLE
Stream end encountered error

### ISSUE THREAD

**Issue by AdiletAbylov** [m1entus/MZFayeClient#1]
Hey, thanks for a great library.
There is the problem (or not): after sometime after connect to server client disconnects with "Stream end encountered" error. Clients reconnects and everything works good, but I am wondering: is it OK?
Private Pub service used as server https://github.com/ryanb/private_pub

**Comment by AdiletAbylov** [comment]
By the way. The problem was because of short timeout period on Thin server. So your client works fine :)

**Comment by m1entus** [comment]
Good to know, thanks :)
