### ISSUE TITLE
the client cannot handle wildcard subscriptions

### ISSUE THREAD

**Issue by kaala** [m1entus/MZFayeClient#16]
The `*` wildcard matches any channel segment. So `/foo/*` matches `/foo/bar` and `/foo/thing` but not `/foo/bar/thing`.
The `**` wildcard matches any channel name recursively. So `/foo/**` matches `/foo/bar`, `/foo/thing` and `/foo/bar/thing`.

**Comment by m1entus** [comment]
Feel free to make PR :)

**Comment by kaala** [comment]
I forked your code, and see you already done this.
It is strange, when I download the zip last week, wildcard is not there
