### ISSUE TITLE
Channel doesn't remove from subscribedChannels after unsubscribe

### ISSUE THREAD

**Issue by AdiletAbylov** [m1entus/MZFayeClient#6]
This causes next problem:
1. Unsubscribe from channel with name, for example "myChannel"
2. Subscribe again to channel "myChannel"
3. Subscribe doesn't work because of lines of code in subscribeToChannel method: 
```objc
} else if (self.subscribedChannels[channel] || !channel) {
        return;
    }
```
Fixed it removing channel from self.subscribedChannels after successful unsubscribe . But I am not sure I did right thing.

**Comment by m1entus** [comment]
Should be fixed
