### ISSUE TITLE
if client is online subscriptions are never removed

### ISSUE THREAD

**Issue by beat843796** [m1entus/MZFayeClient#7]
if you unsubribe from a channel the channel is only be reomved from the subscribedChannels set if client.isConnected is True.

i think this is a bug because when the client is currently not connected you can never unsubribe.

heres a fix for the method:

```
- (void)unsubscribeFromChannel:(NSString *)channel
{
    if (!self.subscribedChannels[channel] || !channel) {
        return;
    }
    
    [self.subscribedChannels removeObjectForKey:channel];
    
    if (self.isConnected) {
        [self sendBayeuxUnsubscribeMessageWithChannel:channel];
    } else {
        
        [self.pendingChannelSubscriptions removeObject:channel];
    }
}
```

**Comment by m1entus** [comment]
Please make pull request

**Comment by beat843796** [comment]
changed to much in your code, ist it possible to create a pull request just for a specific commit?

**Comment by m1entus** [comment]
But i am unsubscribing client when server will do it as a confirmation:

if ([fayeMessage.channel isEqualToString:MZFayeClientBayeuxChannelUnsubscribe]) {

            if ([fayeMessage.successful boolValue]) {
                
                [self.subscribedChannels removeObjectForKey:fayeMessage.subscription];
                [self.pendingChannelSubscriptions removeObject:fayeMessage.subscription];
                [self.openChannelSubscriptions removeObject:fayeMessage.subscription];

**Comment by beat843796** [comment]
true, but you will never be unsubscribed if client is not connected i debuged that for hours

Von meinem iPhone gesendet

**Comment by m1entus** [comment]
Fixed
